apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  labels:
    app: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: student-app
          image: ghcr.io/skaur1604/module_6_part_3:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80