apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student-app
spec:
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer