name: CI-CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-update-gitops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repository
        uses: actions/checkout@v5

      - name: Check required secrets exist
        run: |
          if [ -z "${{ secrets.GITOPS_PAT }}" ]; then echo "GITOPS_PAT is missing"; exit 1; else echo "GITOPS_PAT exists"; fi
          if [ -z "${{ secrets.GITOPS_REPO }}" ]; then echo "GITOPS_REPO is missing"; exit 1; else echo "GITOPS_REPO exists"; fi

      - name: Show repository info
        run: |
          echo "GitHub actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "GitOps repo: ${{ secrets.GITOPS_REPO }}"

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:${{ github.sha }} \
            -t ghcr.io/${{ github.repository }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Clone GitOps repository
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_PAT }}@github.com/${{ secrets.GITOPS_REPO }} gitops-repo

      - name: Check GitOps files
        run: |
          ls -la gitops-repo
          ls -la gitops-repo/k8s

      - name: Update deployment manifest in GitOps repository
        run: |
          sed -i "s|image:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" gitops-repo/k8s/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          cd gitops-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
          git push